### ISSUE TITLE
关于BYM_AI：DeepSeek API Key 分词器BUG和预设的DeepSeek endpoint URL错误导致无法与DeepSeek建立连接

### ISSUE THREAD

**Issue by Kurehava** [zhenxun-org/zhenxun_bot_plugins#111]
+= OS:  Ubuntu Server 24.04.2
```
PRETTY_NAME="Ubuntu 24.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.2 LTS (Noble Numbat)"
VERSION_CODENAME=noble
```
+= zhenxun_bot Version：
`__version__: v0.2.4-2c97eea`

+= 问题以及疑似BUG：

第一：
  在WebUI中输入API Key 时，
  实际保存到config.yaml中的不是整串API Key而是所有的字符都被切分，作为一个Key保存了。
  直接手动输入到config文件中就不会有问题。再次在WebUI中设置时会再次覆盖手动输入的API Key。
  如下所示（不是实际的Key）：
  zhenxun/data/config.yaml:201
  zhenxun/data/configs/plugins2config.yaml:349
  ```
    BYM_AI_CHAT_TOKEN:
      value:
      - x
      - x
      - '-'
      - '0'
      - x
      - '0'
      - '0'
      - x
      - x
      - x
      - x
      - '0'
      - '0'
      - x
      - '0'
      - '0'
      - '0'
      - x
      - '0'
      - '0'
      - '0'
      - '0'
      - x
      - '0'
      - x
      - '0'
      - '0'
      - '0'
      - x
      - x
      - x
      - x
      - x
      - '0'
      - '0'
      help: ai聊天接口密钥，使用列表
      default_value:
  ```

第二：
  可能是预设的DeepSeek的API endpoint URL错误导致404错误。
  zhenxun/plugins/bym_ai/data_source.py: 330

  预设：
  `"DeepSeek": "https://api.deepseek.com",`

  实际上正确的endpoint：
  `"DeepSeek": "https://api.deepseek.com/chat/completions",`

修改以上两点之后，可以正常使用BYM_AI-DeepSeek进行对话，
否则一直处于404状态。只修改第二点(endpoint)会导致一直处于401状态。
[DeepSeek API 文档-错误码](https://api-docs.deepseek.com/zh-cn/quick_start/error_codes)
