### ISSUE TITLE
本地图库插件希望加上之前老的可配置项

### ISSUE THREAD

**Issue by Rod-fish** [zhenxun-org/zhenxun_bot_plugins#57]
以前老版本是有以下这些可配置项的
现在的版本没有这些功能了
主要是需要可配置自动撤回和监控聊天类型
```
image_management:
  # 图库操作
  # IMAGE_DIR_LIST: 公开图库列表，可自定义添加 [如果含有send_setu插件，请不要添加色图库]
  # WITHDRAW_IMAGE_MESSAGE: 自动撤回，参1：延迟撤回发送图库图片的时间(秒)，0 为关闭 | 参2：监控聊天类型，0(私聊) 1(群聊) 2(群聊+私聊)
  # DELETE_IMAGE_LEVEL: 删除图库图片需要的管理员等级
  # MOVE_IMAGE_LEVEL: 移动图库图片需要的管理员等级
  # UPLOAD_IMAGE_LEVEL: 上传图库图片需要的管理员等级
  # SHOW_ID: 是否消息显示图片下标id
  IMAGE_DIR_LIST:
  - 壁纸
  WITHDRAW_IMAGE_MESSAGE:
  - 0
  - 0
  DELETE_IMAGE_LEVEL: 5
  MOVE_IMAGE_LEVEL: 5
  UPLOAD_IMAGE_LEVEL: 5
  SHOW_ID: false
  ```
